language: java

jdk: oraclejdk15

name: Coveralls GitHub Action
uses: coverallsapp/github-action@1.1.3


sudo: false
script:
  - mvn clean
  - mvn test

after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - mvn clean test jacoco:report coveralls:report
